FROM node:10.19.0 as build-stage
WORKDIR /app
#install essential apt package
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i 's|security.debian.org|archive.debian.org/|g' /etc/apt/sources.list
RUN sed -i '/stretch-updates/d' /etc/apt/sources.list
RUN apt update -y
RUN apt install net-tools
# create ssh key dir for git
COPY ./id_rsa ./
RUN mkdir -p /root/.ssh
RUN cp id_rsa /root/.ssh/
RUN chmod 600 /root/.ssh/id_rsa
# copy codes
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8081
# CMD ["npm", "run", "serve"]
CMD ["bash", "-c", "while true; do sleep 1000; done "]